### ISSUE TITLE
checklist function not working

### ISSUE THREAD

**Issue by naddel91** [EnhancedJax/QuickNote#1]
I cannot get checklist function (the circle that should get orange when clicked) to work.
maybe it is a user error, but I tried everything to make it work.

please confirm.

**Comment by EnhancedJax** [comment]
This bug was fixed in the latest release, please update and let me know how it goes

**Comment by naddel91** [comment]
I am on latest version 1.15 and I cannot get the CHECKED marker to work.

**Comment by EnhancedJax** [comment]
Oh sorry, I forgot to push the update. I'll do that tomorrow.

**Comment by naddel91** [comment]
glad to hear. I almost thought I was too silly to check those circles correctly.

**Comment by EnhancedJax** [comment]
The issue should be resolved. Please update and see!
